# Generated by Django 5.0.3 on 2024-03-15 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anaminese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetApp.pet')),
            ],
        ),
    ]
